# Generated by Django 5.2.8 on 2025-11-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_course_discount_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(default='', help_text='Enter the course content separated by commas.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='0 Hours', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(default='', help_text='Enter the requirements separated by commas.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='library_images/'),
        ),
    ]
